/*
 * FileApi
 * File Api V1
 *
 * The version of the OpenAPI document: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.io.File;
import org.openapitools.client.model.FileUploadV2;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UploadRoutesStreamuploadApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public UploadRoutesStreamuploadApi() {
        this(Configuration.getDefaultApiClient());
    }

    public UploadRoutesStreamuploadApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for upload
     * @param files  (required)
     * @param correlationId  (optional)
     * @param isPublic  (optional)
     * @param withoutThumbnail  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Upload a file </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadCall(@javax.annotation.Nonnull List<File> files, @javax.annotation.Nullable String correlationId, @javax.annotation.Nullable Boolean isPublic, @javax.annotation.Nullable Boolean withoutThumbnail, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v1/upload";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (files != null) {
            localVarFormParams.put("files", files);
        }

        if (correlationId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("correlation_id", correlationId));
        }

        if (isPublic != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("is_public", isPublic));
        }

        if (withoutThumbnail != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("without_thumbnail", withoutThumbnail));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call uploadValidateBeforeCall(@javax.annotation.Nonnull List<File> files, @javax.annotation.Nullable String correlationId, @javax.annotation.Nullable Boolean isPublic, @javax.annotation.Nullable Boolean withoutThumbnail, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'files' is set
        if (files == null) {
            throw new ApiException("Missing the required parameter 'files' when calling upload(Async)");
        }

        return uploadCall(files, correlationId, isPublic, withoutThumbnail, _callback);

    }

    /**
     * 
     * 
     * @param files  (required)
     * @param correlationId  (optional)
     * @param isPublic  (optional)
     * @param withoutThumbnail  (optional)
     * @return List&lt;FileUploadV2&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Upload a file </td><td>  -  </td></tr>
     </table>
     */
    public List<FileUploadV2> upload(@javax.annotation.Nonnull List<File> files, @javax.annotation.Nullable String correlationId, @javax.annotation.Nullable Boolean isPublic, @javax.annotation.Nullable Boolean withoutThumbnail) throws ApiException {
        ApiResponse<List<FileUploadV2>> localVarResp = uploadWithHttpInfo(files, correlationId, isPublic, withoutThumbnail);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param files  (required)
     * @param correlationId  (optional)
     * @param isPublic  (optional)
     * @param withoutThumbnail  (optional)
     * @return ApiResponse&lt;List&lt;FileUploadV2&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Upload a file </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<FileUploadV2>> uploadWithHttpInfo(@javax.annotation.Nonnull List<File> files, @javax.annotation.Nullable String correlationId, @javax.annotation.Nullable Boolean isPublic, @javax.annotation.Nullable Boolean withoutThumbnail) throws ApiException {
        okhttp3.Call localVarCall = uploadValidateBeforeCall(files, correlationId, isPublic, withoutThumbnail, null);
        Type localVarReturnType = new TypeToken<List<FileUploadV2>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param files  (required)
     * @param correlationId  (optional)
     * @param isPublic  (optional)
     * @param withoutThumbnail  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Upload a file </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call uploadAsync(@javax.annotation.Nonnull List<File> files, @javax.annotation.Nullable String correlationId, @javax.annotation.Nullable Boolean isPublic, @javax.annotation.Nullable Boolean withoutThumbnail, final ApiCallback<List<FileUploadV2>> _callback) throws ApiException {

        okhttp3.Call localVarCall = uploadValidateBeforeCall(files, correlationId, isPublic, withoutThumbnail, _callback);
        Type localVarReturnType = new TypeToken<List<FileUploadV2>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
