/*
 * FileApi
 * File Api V1
 *
 * The version of the OpenAPI document: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.DownloadBulkRequestUriParams;
import java.io.File;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UploadRoutesDownloadBulkApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public UploadRoutesDownloadBulkApi() {
        this(Configuration.getDefaultApiClient());
    }

    public UploadRoutesDownloadBulkApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for downloadBulk
     * @param downloadBulkRequestUriParams  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Download multiple files as a zip </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call downloadBulkCall(@javax.annotation.Nonnull DownloadBulkRequestUriParams downloadBulkRequestUriParams, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = downloadBulkRequestUriParams;

        // create path and map variables
        String localVarPath = "/api/v1/upload/download-bulk";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call downloadBulkValidateBeforeCall(@javax.annotation.Nonnull DownloadBulkRequestUriParams downloadBulkRequestUriParams, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'downloadBulkRequestUriParams' is set
        if (downloadBulkRequestUriParams == null) {
            throw new ApiException("Missing the required parameter 'downloadBulkRequestUriParams' when calling downloadBulk(Async)");
        }

        return downloadBulkCall(downloadBulkRequestUriParams, _callback);

    }

    /**
     * 
     * 
     * @param downloadBulkRequestUriParams  (required)
     * @return File
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Download multiple files as a zip </td><td>  -  </td></tr>
     </table>
     */
    public File downloadBulk(@javax.annotation.Nonnull DownloadBulkRequestUriParams downloadBulkRequestUriParams) throws ApiException {
        ApiResponse<File> localVarResp = downloadBulkWithHttpInfo(downloadBulkRequestUriParams);
        return localVarResp.getData();
    }

    /**
     * 
     * 
     * @param downloadBulkRequestUriParams  (required)
     * @return ApiResponse&lt;File&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Download multiple files as a zip </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<File> downloadBulkWithHttpInfo(@javax.annotation.Nonnull DownloadBulkRequestUriParams downloadBulkRequestUriParams) throws ApiException {
        okhttp3.Call localVarCall = downloadBulkValidateBeforeCall(downloadBulkRequestUriParams, null);
        Type localVarReturnType = new TypeToken<File>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * 
     * @param downloadBulkRequestUriParams  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Download multiple files as a zip </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call downloadBulkAsync(@javax.annotation.Nonnull DownloadBulkRequestUriParams downloadBulkRequestUriParams, final ApiCallback<File> _callback) throws ApiException {

        okhttp3.Call localVarCall = downloadBulkValidateBeforeCall(downloadBulkRequestUriParams, _callback);
        Type localVarReturnType = new TypeToken<File>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
