/*
 * FileApi
 * File Api V1
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FileUploadV2
 */
public class FileUploadV2Test {
    private final FileUploadV2 model = new FileUploadV2();

    /**
     * Model tests for FileUploadV2
     */
    @Test
    public void testFileUploadV2() {
        // TODO: test FileUploadV2
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'bookmarked'
     */
    @Test
    public void bookmarkedTest() {
        // TODO: test bookmarked
    }

    /**
     * Test the property 'bookmarkedDate'
     */
    @Test
    public void bookmarkedDateTest() {
        // TODO: test bookmarkedDate
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    public void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'correlationId'
     */
    @Test
    public void correlationIdTest() {
        // TODO: test correlationId
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'extension'
     */
    @Test
    public void extensionTest() {
        // TODO: test extension
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'originalFilename'
     */
    @Test
    public void originalFilenameTest() {
        // TODO: test originalFilename
    }

    /**
     * Test the property 'publicResource'
     */
    @Test
    public void publicResourceTest() {
        // TODO: test publicResource
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'thumbnailId'
     */
    @Test
    public void thumbnailIdTest() {
        // TODO: test thumbnailId
    }

    /**
     * Test the property 'updatedDate'
     */
    @Test
    public void updatedDateTest() {
        // TODO: test updatedDate
    }

}
