/*
 * FileApi
 * File Api V1
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * FileUploadV2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-31T20:35:04.006332485+01:00[Europe/Brussels]", comments = "Generator version: 7.17.0")
public class FileUploadV2 {
  public static final String SERIALIZED_NAME_ID = "_id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_BOOKMARKED = "bookmarked";
  @SerializedName(SERIALIZED_NAME_BOOKMARKED)
  @javax.annotation.Nullable
  private Boolean bookmarked;

  public static final String SERIALIZED_NAME_BOOKMARKED_DATE = "bookmarkedDate";
  @SerializedName(SERIALIZED_NAME_BOOKMARKED_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime bookmarkedDate;

  public static final String SERIALIZED_NAME_CONTENT_TYPE = "contentType";
  @SerializedName(SERIALIZED_NAME_CONTENT_TYPE)
  @javax.annotation.Nullable
  private String contentType;

  public static final String SERIALIZED_NAME_CORRELATION_ID = "correlationId";
  @SerializedName(SERIALIZED_NAME_CORRELATION_ID)
  @javax.annotation.Nullable
  private String correlationId;

  public static final String SERIALIZED_NAME_CREATION_DATE = "creationDate";
  @SerializedName(SERIALIZED_NAME_CREATION_DATE)
  @javax.annotation.Nonnull
  private OffsetDateTime creationDate;

  public static final String SERIALIZED_NAME_EXTENSION = "extension";
  @SerializedName(SERIALIZED_NAME_EXTENSION)
  @javax.annotation.Nullable
  private String extension;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_ORIGINAL_FILENAME = "originalFilename";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_FILENAME)
  @javax.annotation.Nonnull
  private String originalFilename;

  public static final String SERIALIZED_NAME_PUBLIC_RESOURCE = "publicResource";
  @SerializedName(SERIALIZED_NAME_PUBLIC_RESOURCE)
  @javax.annotation.Nonnull
  private Boolean publicResource;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  @javax.annotation.Nonnull
  private Long size;

  public static final String SERIALIZED_NAME_THUMBNAIL_ID = "thumbnailId";
  @SerializedName(SERIALIZED_NAME_THUMBNAIL_ID)
  @javax.annotation.Nullable
  private String thumbnailId;

  public static final String SERIALIZED_NAME_UPDATED_DATE = "updatedDate";
  @SerializedName(SERIALIZED_NAME_UPDATED_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime updatedDate;

  public FileUploadV2() {
  }

  public FileUploadV2 id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public FileUploadV2 bookmarked(@javax.annotation.Nullable Boolean bookmarked) {
    this.bookmarked = bookmarked;
    return this;
  }

  /**
   * Get bookmarked
   * @return bookmarked
   */
  @javax.annotation.Nullable
  public Boolean getBookmarked() {
    return bookmarked;
  }

  public void setBookmarked(@javax.annotation.Nullable Boolean bookmarked) {
    this.bookmarked = bookmarked;
  }


  public FileUploadV2 bookmarkedDate(@javax.annotation.Nullable OffsetDateTime bookmarkedDate) {
    this.bookmarkedDate = bookmarkedDate;
    return this;
  }

  /**
   * Get bookmarkedDate
   * @return bookmarkedDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getBookmarkedDate() {
    return bookmarkedDate;
  }

  public void setBookmarkedDate(@javax.annotation.Nullable OffsetDateTime bookmarkedDate) {
    this.bookmarkedDate = bookmarkedDate;
  }


  public FileUploadV2 contentType(@javax.annotation.Nullable String contentType) {
    this.contentType = contentType;
    return this;
  }

  /**
   * Get contentType
   * @return contentType
   */
  @javax.annotation.Nullable
  public String getContentType() {
    return contentType;
  }

  public void setContentType(@javax.annotation.Nullable String contentType) {
    this.contentType = contentType;
  }


  public FileUploadV2 correlationId(@javax.annotation.Nullable String correlationId) {
    this.correlationId = correlationId;
    return this;
  }

  /**
   * Get correlationId
   * @return correlationId
   */
  @javax.annotation.Nullable
  public String getCorrelationId() {
    return correlationId;
  }

  public void setCorrelationId(@javax.annotation.Nullable String correlationId) {
    this.correlationId = correlationId;
  }


  public FileUploadV2 creationDate(@javax.annotation.Nonnull OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

  /**
   * Get creationDate
   * @return creationDate
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(@javax.annotation.Nonnull OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }


  public FileUploadV2 extension(@javax.annotation.Nullable String extension) {
    this.extension = extension;
    return this;
  }

  /**
   * Get extension
   * @return extension
   */
  @javax.annotation.Nullable
  public String getExtension() {
    return extension;
  }

  public void setExtension(@javax.annotation.Nullable String extension) {
    this.extension = extension;
  }


  public FileUploadV2 name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public FileUploadV2 originalFilename(@javax.annotation.Nonnull String originalFilename) {
    this.originalFilename = originalFilename;
    return this;
  }

  /**
   * Get originalFilename
   * @return originalFilename
   */
  @javax.annotation.Nonnull
  public String getOriginalFilename() {
    return originalFilename;
  }

  public void setOriginalFilename(@javax.annotation.Nonnull String originalFilename) {
    this.originalFilename = originalFilename;
  }


  public FileUploadV2 publicResource(@javax.annotation.Nonnull Boolean publicResource) {
    this.publicResource = publicResource;
    return this;
  }

  /**
   * Get publicResource
   * @return publicResource
   */
  @javax.annotation.Nonnull
  public Boolean getPublicResource() {
    return publicResource;
  }

  public void setPublicResource(@javax.annotation.Nonnull Boolean publicResource) {
    this.publicResource = publicResource;
  }


  public FileUploadV2 size(@javax.annotation.Nonnull Long size) {
    this.size = size;
    return this;
  }

  /**
   * Get size
   * minimum: 0
   * @return size
   */
  @javax.annotation.Nonnull
  public Long getSize() {
    return size;
  }

  public void setSize(@javax.annotation.Nonnull Long size) {
    this.size = size;
  }


  public FileUploadV2 thumbnailId(@javax.annotation.Nullable String thumbnailId) {
    this.thumbnailId = thumbnailId;
    return this;
  }

  /**
   * Get thumbnailId
   * @return thumbnailId
   */
  @javax.annotation.Nullable
  public String getThumbnailId() {
    return thumbnailId;
  }

  public void setThumbnailId(@javax.annotation.Nullable String thumbnailId) {
    this.thumbnailId = thumbnailId;
  }


  public FileUploadV2 updatedDate(@javax.annotation.Nullable OffsetDateTime updatedDate) {
    this.updatedDate = updatedDate;
    return this;
  }

  /**
   * Get updatedDate
   * @return updatedDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedDate() {
    return updatedDate;
  }

  public void setUpdatedDate(@javax.annotation.Nullable OffsetDateTime updatedDate) {
    this.updatedDate = updatedDate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileUploadV2 fileUploadV2 = (FileUploadV2) o;
    return Objects.equals(this.id, fileUploadV2.id) &&
        Objects.equals(this.bookmarked, fileUploadV2.bookmarked) &&
        Objects.equals(this.bookmarkedDate, fileUploadV2.bookmarkedDate) &&
        Objects.equals(this.contentType, fileUploadV2.contentType) &&
        Objects.equals(this.correlationId, fileUploadV2.correlationId) &&
        Objects.equals(this.creationDate, fileUploadV2.creationDate) &&
        Objects.equals(this.extension, fileUploadV2.extension) &&
        Objects.equals(this.name, fileUploadV2.name) &&
        Objects.equals(this.originalFilename, fileUploadV2.originalFilename) &&
        Objects.equals(this.publicResource, fileUploadV2.publicResource) &&
        Objects.equals(this.size, fileUploadV2.size) &&
        Objects.equals(this.thumbnailId, fileUploadV2.thumbnailId) &&
        Objects.equals(this.updatedDate, fileUploadV2.updatedDate);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, bookmarked, bookmarkedDate, contentType, correlationId, creationDate, extension, name, originalFilename, publicResource, size, thumbnailId, updatedDate);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileUploadV2 {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    bookmarked: ").append(toIndentedString(bookmarked)).append("\n");
    sb.append("    bookmarkedDate: ").append(toIndentedString(bookmarkedDate)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    correlationId: ").append(toIndentedString(correlationId)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    originalFilename: ").append(toIndentedString(originalFilename)).append("\n");
    sb.append("    publicResource: ").append(toIndentedString(publicResource)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    thumbnailId: ").append(toIndentedString(thumbnailId)).append("\n");
    sb.append("    updatedDate: ").append(toIndentedString(updatedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("_id", "bookmarked", "bookmarkedDate", "contentType", "correlationId", "creationDate", "extension", "name", "originalFilename", "publicResource", "size", "thumbnailId", "updatedDate"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("_id", "creationDate", "originalFilename", "publicResource", "size"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FileUploadV2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FileUploadV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in FileUploadV2 is not found in the empty JSON string", FileUploadV2.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FileUploadV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `FileUploadV2` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FileUploadV2.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("_id").toString()));
      }
      if ((jsonObj.get("contentType") != null && !jsonObj.get("contentType").isJsonNull()) && !jsonObj.get("contentType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `contentType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("contentType").toString()));
      }
      if ((jsonObj.get("correlationId") != null && !jsonObj.get("correlationId").isJsonNull()) && !jsonObj.get("correlationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `correlationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("correlationId").toString()));
      }
      if ((jsonObj.get("extension") != null && !jsonObj.get("extension").isJsonNull()) && !jsonObj.get("extension").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `extension` to be a primitive type in the JSON string but got `%s`", jsonObj.get("extension").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("originalFilename").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `originalFilename` to be a primitive type in the JSON string but got `%s`", jsonObj.get("originalFilename").toString()));
      }
      if ((jsonObj.get("thumbnailId") != null && !jsonObj.get("thumbnailId").isJsonNull()) && !jsonObj.get("thumbnailId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `thumbnailId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("thumbnailId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FileUploadV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FileUploadV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FileUploadV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FileUploadV2.class));

       return (TypeAdapter<T>) new TypeAdapter<FileUploadV2>() {
           @Override
           public void write(JsonWriter out, FileUploadV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FileUploadV2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FileUploadV2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FileUploadV2
   * @throws IOException if the JSON string is invalid with respect to FileUploadV2
   */
  public static FileUploadV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FileUploadV2.class);
  }

  /**
   * Convert an instance of FileUploadV2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

