/*
 * FileApi
 * File Api V1
 *
 * The version of the OpenAPI document: 0.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.FileUploadV2;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import org.openapitools.client.JSON;

/**
 * OpenApiDocUploadFormSimpleFile
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-10T17:45:30.149167520+01:00[Europe/Brussels]", comments = "Generator version: 7.17.0")
public class OpenApiDocUploadFormSimpleFile {
  public static final String SERIALIZED_NAME_FILE = "file";
  @SerializedName(SERIALIZED_NAME_FILE)
  @javax.annotation.Nonnull
  private File _file;

  public static final String SERIALIZED_NAME_FILE_UPLOAD = "file_upload";
  @SerializedName(SERIALIZED_NAME_FILE_UPLOAD)
  @javax.annotation.Nullable
  private FileUploadV2 fileUpload;

  public OpenApiDocUploadFormSimpleFile() {
  }

  public OpenApiDocUploadFormSimpleFile _file(@javax.annotation.Nonnull File _file) {
    this._file = _file;
    return this;
  }

  /**
   * Get _file
   * @return _file
   */
  @javax.annotation.Nonnull
  public File getFile() {
    return _file;
  }

  public void setFile(@javax.annotation.Nonnull File _file) {
    this._file = _file;
  }


  public OpenApiDocUploadFormSimpleFile fileUpload(@javax.annotation.Nullable FileUploadV2 fileUpload) {
    this.fileUpload = fileUpload;
    return this;
  }

  /**
   * Get fileUpload
   * @return fileUpload
   */
  @javax.annotation.Nullable
  public FileUploadV2 getFileUpload() {
    return fileUpload;
  }

  public void setFileUpload(@javax.annotation.Nullable FileUploadV2 fileUpload) {
    this.fileUpload = fileUpload;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OpenApiDocUploadFormSimpleFile openApiDocUploadFormSimpleFile = (OpenApiDocUploadFormSimpleFile) o;
    return Objects.equals(this._file, openApiDocUploadFormSimpleFile._file) &&
        Objects.equals(this.fileUpload, openApiDocUploadFormSimpleFile.fileUpload);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(_file, fileUpload);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OpenApiDocUploadFormSimpleFile {\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    fileUpload: ").append(toIndentedString(fileUpload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("file", "file_upload"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("file"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OpenApiDocUploadFormSimpleFile
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OpenApiDocUploadFormSimpleFile.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in OpenApiDocUploadFormSimpleFile is not found in the empty JSON string", OpenApiDocUploadFormSimpleFile.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OpenApiDocUploadFormSimpleFile.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `OpenApiDocUploadFormSimpleFile` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : OpenApiDocUploadFormSimpleFile.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `file_upload`
      if (jsonObj.get("file_upload") != null && !jsonObj.get("file_upload").isJsonNull()) {
        FileUploadV2.validateJsonElement(jsonObj.get("file_upload"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OpenApiDocUploadFormSimpleFile.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OpenApiDocUploadFormSimpleFile' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OpenApiDocUploadFormSimpleFile> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OpenApiDocUploadFormSimpleFile.class));

       return (TypeAdapter<T>) new TypeAdapter<OpenApiDocUploadFormSimpleFile>() {
           @Override
           public void write(JsonWriter out, OpenApiDocUploadFormSimpleFile value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OpenApiDocUploadFormSimpleFile read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OpenApiDocUploadFormSimpleFile given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OpenApiDocUploadFormSimpleFile
   * @throws IOException if the JSON string is invalid with respect to OpenApiDocUploadFormSimpleFile
   */
  public static OpenApiDocUploadFormSimpleFile fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OpenApiDocUploadFormSimpleFile.class);
  }

  /**
   * Convert an instance of OpenApiDocUploadFormSimpleFile to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

