/*
 * FileApi
 * File Api V1
 *
 * The version of the OpenAPI document: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.io.File;
import org.openapitools.client.model.FileUploadV2;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadRoutesStreamuploadApi
 */
@Disabled
public class UploadRoutesStreamuploadApiTest {

    private final UploadRoutesStreamuploadApi api = new UploadRoutesStreamuploadApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadTest() throws ApiException {
        List<File> files = null;
        String correlationId = null;
        Boolean isPublic = null;
        Boolean withoutThumbnail = null;
        List<FileUploadV2> response = api.upload(files, correlationId, isPublic, withoutThumbnail);
        // TODO: test validations
    }

}
