/*
 * FileApi
 * File Api V1
 *
 * The version of the OpenAPI document: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DownloadBulkRequestUriParams;
import java.io.File;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadRoutesDownloadBulkApi
 */
@Disabled
public class UploadRoutesDownloadBulkApiTest {

    private final UploadRoutesDownloadBulkApi api = new UploadRoutesDownloadBulkApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadBulkTest() throws ApiException {
        DownloadBulkRequestUriParams downloadBulkRequestUriParams = null;
        File response = api.downloadBulk(downloadBulkRequestUriParams);
        // TODO: test validations
    }

}
