/*
 * FileApi
 * File Api V1
 *
 * The version of the OpenAPI document: 0.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.FileUploadV2;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadRoutesMetadataApi
 */
@Disabled
public class UploadRoutesMetadataApiTest {

    private final UploadRoutesMetadataApi api = new UploadRoutesMetadataApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void metadataTest() throws ApiException {
        String id = null;
        FileUploadV2 response = api.metadata(id);
        // TODO: test validations
    }

}
