/*
 * FileApi
 * File Api V1
 *
 * The version of the OpenAPI document: 0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DownloadBulkRequestUriParams;
import java.io.File;
import org.openapitools.client.model.FileUploadV2;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadRoutesApi
 */
@Disabled
public class UploadRoutesApiTest {

    private final UploadRoutesApi api = new UploadRoutesApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteByIdTest() throws ApiException {
        String id = null;
        api.deleteById(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadTest() throws ApiException {
        String id = null;
        File response = api.download(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadBulkTest() throws ApiException {
        DownloadBulkRequestUriParams downloadBulkRequestUriParams = null;
        File response = api.downloadBulk(downloadBulkRequestUriParams);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAllUploadsTest() throws ApiException {
        String correlationId = null;
        List<FileUploadV2> response = api.findAllUploads(correlationId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void makeThumbTest() throws ApiException {
        String id = null;
        FileUploadV2 response = api.makeThumb(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void metadataTest() throws ApiException {
        String id = null;
        FileUploadV2 response = api.metadata(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void pingTest() throws ApiException {
        api.ping();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadTest() throws ApiException {
        List<File> files = null;
        String correlationId = null;
        Boolean isPublic = null;
        Boolean withoutThumbnail = null;
        List<FileUploadV2> response = api.upload(files, correlationId, isPublic, withoutThumbnail);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadUpdateTest() throws ApiException {
        String id = null;
        File _file = null;
        FileUploadV2 response = api.uploadUpdate(id, _file);
        // TODO: test validations
    }

}
