/*
 * FileApi
 * File Api V1
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.io.File;
import org.openapitools.client.model.FileUploadV2;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadRoutesApi
 */
@Disabled
public class UploadRoutesApiTest {

    private final UploadRoutesApi api = new UploadRoutesApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteByIdTest() throws ApiException {
        String id = null;
        api.deleteById(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadTest() throws ApiException {
        String id = null;
        File response = api.download(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void findAllUploadsTest() throws ApiException {
        String correlationId = null;
        List<FileUploadV2> response = api.findAllUploads(correlationId);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void metadataTest() throws ApiException {
        String id = null;
        FileUploadV2 response = api.metadata(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadTest() throws ApiException {
        File fileBytes = null;
        String correlationId = null;
        String id = null;
        Boolean isPublic = null;
        Boolean withoutThumbnail = null;
        FileUploadV2 response = api.upload(fileBytes, correlationId, id, isPublic, withoutThumbnail);
        // TODO: test validations
    }

}
